version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: foodops-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: foodops-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: foodops-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api/v1
      - VITE_SERVER_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  mongo_data: